name: VengefulMobs
version: '1.1.1'
main: dev.melncat.vengefulmobs.VengefulMobs
api-version: 1.18
authors: [ MelnCat ]
description: Makes passive mobs fight back.
commands:
  vengefulmobs:
    usage: /<command> [reload]
    description: The main plugin command